pull_request_rules:
  - name: Automatic merge dependency update on approval
    conditions:
      - "#approved-reviews-by>=1"
      - label=dependencies
      - author=dependabot[bot]
      - check-success=Community-TC (pull_request)
    actions:
      merge:
        method: squash
