version: 1
reporting: checks-v1
policy:
  pullRequests: public
tasks:
  $let:
    user: ${event.sender.login}

    head_branch:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.ref}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: ${event.release.target_commitish}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
  in:
    $if: >
      (tasks_for == "github-pull-request" && event.action in ["opened", "reopened", "synchronize"])
      || (tasks_for == "github-push" && event["ref"] == "refs/heads/master")
    then:
      - taskId: { $eval: as_slugid("tests_task") }
        created: { $fromNow: "" }
        deadline: { $fromNow: "1 hour" }
        provisionerId: proj-relman
        workerType: ci
        payload:
          maxRunTime: 3600
          image: python:3.10
          env:
            TOX_ENV: py310
            COVERALLS_REPO_TOKEN: VWnjgqWLHfmgSQMJPFdIRYIG5ontiAGl6
          command:
            - "/bin/bash"
            - "-lcx"
            - "git clone --quiet ${repository} bugbot &&
              cd bugbot &&
              git -c advice.detachedHead=false checkout ${head_rev} &&
              chmod +x pre-commit/check_json_indentation.py &&
              pip install --quiet -r requirements-test.txt &&
              pre-commit run --all-files --show-diff-on-failure &&
              tox -e $TOX_ENV &&
              coveralls"
        metadata:
          name: bugbot tests
          description: bugbot tests
          owner: mcastelluccio@mozilla.com
          source: ${repository}/raw/${head_rev}/.taskcluster.yml
