# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import pytest

from bugbot.rules.duplicate_copy_metadata import DuplicateCopyMetadata


@pytest.fixture
def duplicate_metadata_bugs():
    comments = [
        "The following field has been copied from a duplicate bug:\n| Field | Value | Source |\n| ----- | ----- | ------ |\n| Severity | S3 | bug 1790853 |\n\n\nFor more information, please visit [BugBot documentation](https://wiki.mozilla.org/BugBot#duplicate_copy_metadata.py).",
        "The following fields have been copied from duplicate bugs:\n| Field | Value | Source |\n| ----- | ----- | ------ |\n| Keywords | access | bug 1677341 |\n| Severity | S3 | bug 1677341 and bug 1688533 |\n| Whiteboard | [access-s2] | bug 1677341 |\n\n\nFor more information, please visit [BugBot documentation](https://wiki.mozilla.org/BugBot#duplicate_copy_metadata.py).",
    ]

    return [
        {
            "comments": [
                {
                    "text": comment,
                    "author": "release-mgmt-account-bot@mozilla.tld",
                },
            ],
        }
        for comment in comments
    ]


def test_get_previously_copied_fields(duplicate_metadata_bugs):
    rule = DuplicateCopyMetadata()

    assert rule.get_previously_copied_fields(duplicate_metadata_bugs[0]) == {"severity"}
    assert rule.get_previously_copied_fields(duplicate_metadata_bugs[1]) == {
        "severity",
        "whiteboard",
        "keywords",
    }

    # Test based on a comment generated by the rule
    bug = {"id": "1"}
    copied_fields = [
        ("cf_accessibility_severity", "s1", "13"),
    ]
    rule.set_autofix(bug, copied_fields)
    comment = rule.get_autofix_change()["1"]["comment"]["body"]
    bug_with_comment = {
        "comments": [
            {
                "text": comment,
                "author": "release-mgmt-account-bot@mozilla.tld",
            }
        ]
    }
    assert rule.get_previously_copied_fields(bug_with_comment) == {
        "cf_accessibility_severity"
    }
