# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import unittest

from bugbot.rules.duplicate_copy_metadata import DuplicateCopyMetadata


class TestDuplicateCopyMetadata(unittest.TestCase):
    comments = [
        "The following field has been copied from a duplicate bug:\n| Field | Value | Source |\n| ----- | ----- | ------ |\n| Severity | S3 | bug 1790853 |\n\n\nFor more information, please visit [BugBot documentation](https://wiki.mozilla.org/Release_Management/autonag#duplicate_copy_metadata.py).",
        "The following fields have been copied from duplicate bugs:\n| Field | Value | Source |\n| ----- | ----- | ------ |\n| Keywords | access | bug 1677341 |\n| Severity | S3 | bug 1677341 and bug 1688533 |\n| Whiteboard | [access-s2] | bug 1677341 |\n\n\nFor more information, please visit [BugBot documentation](https://wiki.mozilla.org/Release_Management/autonag#duplicate_copy_metadata.py).",
    ]

    bugs = [
        {
            "comments": [
                {
                    "text": comment,
                    "author": "release-mgmt-account-bot@mozilla.tld",
                },
            ],
        }
        for comment in comments
    ]

    def test_get_previously_copied_fields(self):

        tool = DuplicateCopyMetadata()

        self.assertEqual(
            tool.get_previously_copied_fields(self.bugs[0]),
            {"severity"},
        )
        self.assertEqual(
            tool.get_previously_copied_fields(self.bugs[1]),
            {"severity", "whiteboard", "keywords"},
        )

        # Test based on a comment generated by the tool
        bug = {"id": "1", "whiteboard": ""}
        copied_fields = [
            ("whiteboard", "[access-s1]", "13"),
        ]
        tool.set_autofix(bug, copied_fields)
        comment = tool.get_autofix_change()["1"]["comment"]["body"]
        bug_with_comment = {
            "comments": [
                {
                    "text": comment,
                    "author": "release-mgmt-account-bot@mozilla.tld",
                }
            ]
        }
        self.assertEqual(
            tool.get_previously_copied_fields(bug_with_comment),
            {"whiteboard"},
        )
