"""Init the database

Revision ID: ac0a01dcb3a9
Revises:
Create Date: 2019-04-11 18:51:21.056683

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ac0a01dcb3a9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "autonag_extras",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("extra", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("extra"),
    )
    op.create_table(
        "autonag_tools",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "autonag_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "autonag_bugchanges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tool_id", sa.Integer(), nullable=True),
        sa.Column("extra_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Integer(), nullable=True),
        sa.Column("bugid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["extra_id"], ["autonag_extras.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tool_id"], ["autonag_tools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "autonag_emails",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tool_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("extra_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Integer(), nullable=True),
        sa.Column("result", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["extra_id"], ["autonag_extras.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tool_id"], ["autonag_tools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["autonag_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("autonag_emails")
    op.drop_table("autonag_bugchanges")
    op.drop_table("autonag_users")
    op.drop_table("autonag_tools")
    op.drop_table("autonag_extras")
    # ### end Alembic commands ###
